GRID_ROWS = 20
GRID_COLS = 10
BLOCK_SIZE = 30

GRID_BACKGROUND_COLOR = (0, 0, 0)
GRID_LINE_COLOR = (36, 36, 36)
GRID_LINE_WIDTH = 1

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

BOARD_WIDTH = GRID_COLS * BLOCK_SIZE
BOARD_HEIGHT = GRID_ROWS * BLOCK_SIZE